# ESPHome ESP8266 configuration file
esphome:
  name: esp-arduino-tft-weather
  friendly_name: ESP-Arduino-TFT-Weather

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<RELPLACE_ME>"  #! Replace with your actual encryption key

ota:
  - platform: esphome
    password: "<RELPLACE_ME>"  #! Replace with your actual OTA password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Arduino-Tft-Weather"
    password: "<RELPLACE_ME>"  #! Replace with your actual fallback password

captive_portal:

# Read the pre-formatted payload from Home Assistant as text
text_sensor:
  - platform: homeassistant
    entity_id: sensor.uart_weather_payload
    id: uart_weather_payload

# UART setup: only TX needed
uart:
  id: uart_bus
  tx_pin: D1  # GPIO5 on NodeMCU V3
  baud_rate: 9600
  debug:
    direction: TX  # Log outgoing UART data for debugging

# Every minute, log and send the payload string plus newline
interval:
  - interval: 60s
    then:
      - uart.write:
          id: uart_bus
          data: !lambda |-
            // Append newline for Arduino
            std::string s = id(uart_weather_payload).state + "\n";
            ESP_LOGD("UART", "Sending payload: '%s'", s.c_str());
            return std::vector<uint8_t>(s.begin(), s.end());


